version: '3'

services:
  wordpress:
    image: wordpress
    container_name: my-wordpress
    restart: always
    ports:
      - "8080:80"  # Map container's port 80 to host's port 8000
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - wordpress_data:/var/www/html

  db: 
    image: mysql:5.7
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data: